### ISSUE TITLE
I have some fixes for "TermEmulatorDemo.py".

### ISSUE THREAD

**Issue by avose** [sivachandran/TermEmulator#10]
I have some fixes for:

The "TermEmulator/TermEmulatorDemo.py" doesn't seem to work in Python3, as I think you've pointed out in another issue on there. I was able to make some minor modifications and get basic functionality to work: I can at least run the BASH shell and interact with it, I can run "ls" with working colors, and I was even able to run Emacs and get that going (except the ALT key wasn't working for the "meta" commands in Emacs).

Are you interested in having the above fixes? It's not a full Python3 update, but it does allow basic functionality to work. How do you want me to send this to you? Do you want me to fork the repo and do a pull request from my fork? Or can you add permissions for me to your repo? If you do that, I can just make a branch for doing some Python3 updates and make pull requests from there into master / main branch? How do you prefer I move forward here?

--

In the long run, I'm very interested in this project. I wan to improve it. I also want to use the functionality in a new tool I'm making. I'm making a new tool with a 3D OpenGL visualization for filesystem and code layout that will be at the left of a window. I'll then have a section on the right of the window running a terminal, based on this TermEmulator Project. The two sides will interact, where the 3D view and the Terminal will be linked: clicking and interacting with the 3D OpenGL view will issue commands into the terminal, and commands in the terminal will update the 3D OpenGL view.

It seems this great TermEmulator project could work perfectly for the right terminal side of my project.

**Comment by sivachandran** [comment]
Thanks for fixing the issues. I would love to have your changes merged. Please fork and raise PR for the upstream.

Glad to hear your potential usage of TermEmulator. Will support and help however I can. 

--
Cheers

**Comment by avose** [comment]
OK, will fork and send a pull request sometime next week, Thanks!

**Comment by avose** [comment]
I created a fork and added the very small changes needed to get it to run on my system; the pull request is there now.

I'll be in touch over email soon with a link to our new "GLShell" project repo that uses your TermEmulator code.
