### ISSUE TITLE
Error on Windows OS

### ISSUE THREAD

**Issue by pydemo** [sivachandran/TermEmulator#9]
C:\tmp\Python\Python38-32>python -m pip install TermEmulator
Collecting TermEmulator
  Downloading TermEmulator-1.0.2.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\tmp\Python\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alex_\\AppData\\Local\\Temp\\pip-install-g1qbb379\\termemulator\\setup.py'"'"'; __file__='"'"'C:\\Users\\alex_\\AppData\\Local\\Temp\\pip-install-g1qbb379\\termemulator\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\alex_\AppData\Local\Temp\pip-pip-egg-info-is8q0jsd'
         cwd: C:\Users\alex_\AppData\Local\Temp\pip-install-g1qbb379\termemulator\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\alex_\AppData\Local\Temp\pip-install-g1qbb379\termemulator\setup.py", line 5, in <module>
        long_description = (file('README.rst').read() +
    NameError: name 'file' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sivachandran** [comment]
Fixed by e0d4a2e
